plugins {
    id 'multiloader-loader'
    id 'fabric-loom'
}

loom {
    def aw = project(':common').file("src/main/resources/${mod_id}.accesswidener")
    if (aw.exists()) {
        accessWidenerPath.set(aw)
    }
    mixin {
        defaultRefmapName.set("${mod_id}.refmap.json")
    }
    runs {
        client {
            client()
            setConfigName('Fabric Client')
            ideConfigGenerated(true)
            runDir('runs/client')
        }
        server {
            server()
            setConfigName('Fabric Server')
            ideConfigGenerated(true)
            runDir('runs/server')
        }
    }
}

repositories {
    mavenCentral()

    maven {
        name = "CurseMaven"
        url = uri("https://cursemaven.com")

        content {
            includeGroup "curse.maven"
        }
    }

    maven {
        name = "Modrinth Maven"
        url = uri("https://api.modrinth.com/maven")

        content {
            includeGroup "maven.modrinth"
        }
    }

    maven {
        name = "Forge Config API Port Maven"
        url = uri("https://raw.githubusercontent.com/Fuzss/modresources/main/maven/")
        content {
            includeGroup "fuzs.forgeconfigapiport"
        }
    }

    maven {
        name = "DevAuth Maven"
        url = uri("https://pkgs.dev.azure.com/djtheredstoner/DevAuth/_packaging/public/maven/v1")
        content {
            includeGroup "me.djtheredstoner"
        }
    }

    maven {
        name = "FTB Maven"
        url = uri("https://maven.ftb.dev/releases")
        content {
            includeGroup "dev.ftb.mods"
        }
    }

    maven {
        name = "Xaero Maven"
        url = uri("https://chocolateminecraft.com/maven")
        content {
            includeGroup "xaero.lib"
        }
    }

    maven {
        name = "Journeymap API MAven"
        url = uri("https://jm.gserv.me/repository/maven-public/")
        content {
            includeGroup "info.journeymap"
        }
    }

    maven {
        name = "Homeostatic Seasons"
        url = uri("https://raw.githubusercontent.com/wendall911/maven/main/")
        content {
            includeGroup "com.github.wendall911.climatesettings"
            includeGroup "com.github.wendall911.homeostaticseasons"
            includeGroup "technology.roughness.whitenoise"
        }
    }
}

dependencies {
    minecraft "com.mojang:minecraft:${minecraft_version}"
    mappings loom.layered {
        officialMojangMappings()
        parchment("org.parchmentmc.data:parchment-${parchment_minecraft}:${parchment_version}@zip")
    }
    modImplementation "net.fabricmc:fabric-loader:${fabric_loader_version}"
    modImplementation "net.fabricmc.fabric-api:fabric-api:${fabric_api_version}"

    implementation group: 'com.google.code.findbugs', name: 'jsr305', version: '3.0.1'

    // Fabric Seasons + Extras
    modCompileOnly("maven.modrinth:fabric-seasons:${project.fabric_seasons_version}")
    modCompileOnly("maven.modrinth:fabric-seasons-extras:${project.fabric_seasons_extras_version}")

    // Serene Seasons
    modCompileOnly "com.github.glitchfiend:SereneSeasons-fabric:${project.serene_seasons_version}"
    modCompileOnly "com.github.glitchfiend:GlitchCore-fabric:${project.glitchcore_version}"
    modCompileOnly("net.jodah:typetools:0.6.3")

    // Homeostatic Seasons
    modCompileOnly group: 'com.github.wendall911.homeostaticseasons', name: "homeostaticseasons-${project.minecraft_version}-fabric", version: "${project.homeostatic_seasons_version}"
    modCompileOnly group: 'technology.roughness.whitenoise', name: "whitenoise-${project.minecraft_version}-fabric", version: "${project.whitenoise_version}"
    modCompileOnly group: 'com.github.wendall911.climatesettings', name: "climatesettings-${project.minecraft_version}-fabric", version: "${project.climatesettings_version}"

    // Xaero's Minimap
    modCompileOnly("maven.modrinth:xaeros-minimap:${project.xaeros_minimap_version}_Fabric_${project.xaero_mc_version}") {
        exclude group: 'net.fabricmc', module: 'fabric-loader'
    }
    modCompileOnly "xaero.lib:xaerolib-fabric-${project.xaero_mc_version}:${project.xaero_lib_version}"

    // JourneyMap
    modCompileOnlyApi group: 'info.journeymap', name: 'journeymap-api-fabric', version: project.journeymap_api_version, changing: true
    modCompileOnly("maven.modrinth:journeymap:${project.journeymap_version_fabric}") {
        exclude group: 'net.fabricmc', module: 'fabric-loader'
    }

    // FTB Chunks + Dependencies
    modCompileOnly "dev.ftb.mods:ftb-library-fabric:${project.ftb_library_version}"
    modCompileOnly "dev.ftb.mods:ftb-teams-fabric:${project.ftb_teams_version}"
    modCompileOnly "dev.ftb.mods:ftb-chunks-fabric:${project.ftb_chunks_version}"
    modCompileOnly "dev.architectury:architectury-fabric:${project.architectury_version}"

    // Map Atlases
    modCompileOnly("maven.modrinth:map-atlases:${project.map_atlases_version_fabric}") {
        exclude group: 'net.fabricmc', module: 'fabric-loader'
    }
    modCompileOnly("maven.modrinth:moonlight:${project.moonlight_version_fabric}") {
        exclude group: 'net.fabricmc', module: 'fabric-loader'
    }

    // Trinkets
    modCompileOnly("dev.emi:trinkets:${project.trinkets_version}") {
        exclude group: 'net.fabricmc', module: 'fabric-loader'
    }

    // Accessories
    modCompileOnly "dev.onyxstudios.cardinal-components-api:cardinal-components-base:${project.cardinal_components_version}"
    modCompileOnly "dev.onyxstudios.cardinal-components-api:cardinal-components-entity:${project.cardinal_components_version}"
    modCompileOnly("io.wispforest:accessories-fabric:${project.accessories_version}")
    modCompileOnly("me.shedaniel.cloth:cloth-config-fabric:${project.cloth_config_version}") {
        exclude group: 'net.fabricmc', module: 'fabric-loader'
    }

    // Forge Config API Port
    modApi "fuzs.forgeconfigapiport:forgeconfigapiport-fabric:${project.forge_config_api_port_version}"
    modImplementation("maven.modrinth:forge-config-api-port:v${project.forge_config_api_port_version}-${project.minecraft_version}-Fabric") {
        exclude group: 'net.fabricmc', module: 'fabric-loader'
    }

    // Development QOL
    modLocalRuntime("me.djtheredstoner:DevAuth-fabric:${project.devauth_version}")
//    modLocalRuntime "maven.modrinth:sodium:${project.sodium_version_fabric}"
    modLocalRuntime "com.terraformersmc:modmenu:${project.modmenu_version}"
//    modLocalRuntime "maven.modrinth:text-animator:${project.text_animator_version_fabric}"

    // Season Mod Dev Tests (Fabric)
    // See root gradle.properties to choose which to use at runtime.
    switch (project.season_mod_fabric.toLowerCase(Locale.ROOT)) {
        case "serene":
            modLocalRuntime "com.github.glitchfiend:SereneSeasons-fabric:${project.serene_seasons_version}"
            modLocalRuntime "com.github.glitchfiend:GlitchCore-fabric:${project.glitchcore_version}"
            break
        case "fabric":
            modImplementation("maven.modrinth:fabric-seasons:${project.fabric_seasons_version}")
            break
        case "fabric+extra":
            modImplementation("maven.modrinth:fabric-seasons:${project.fabric_seasons_version}")
            modImplementation("maven.modrinth:fabric-seasons-extras:${project.fabric_seasons_extras_version}")
            break
        case "homeostatic":
            modImplementation "maven.modrinth:homeostatic-seasons:${project.minecraft_version}-${project.homeostatic_seasons_version}-fabric"
            break
        default: println("Unknown season mod specified: ${project.season_mod_fabric}. Must be serene or fabric")
    }

    // Minimap Mod Dev Tests
    // See root gradle.properties to choose which to use at runtime.
    switch (project.minimap_mod.toLowerCase(Locale.ROOT)) {
        case "xaero":
            modLocalRuntime("maven.modrinth:xaeros-minimap:${project.xaeros_minimap_version}_Fabric_${project.xaero_mc_version}")
            modImplementation "xaero.lib:xaerolib-fabric-${project.xaero_mc_version}:${project.xaero_lib_version}"
            break
        case "journey":
            modImplementation group: 'info.journeymap', name: 'journeymap-api-fabric', version: project.journeymap_api_version, changing: true
            modLocalRuntime("maven.modrinth:journeymap:${project.journeymap_version_fabric}")
            modLocalRuntime("maven.modrinth:common-network:${project.common_network_version}-fabric")
            break
        case "ftb":
            modLocalRuntime "dev.ftb.mods:ftb-library-fabric:${project.ftb_library_version}"
            modLocalRuntime "dev.ftb.mods:ftb-teams-fabric:${project.ftb_teams_version}"
            modLocalRuntime "dev.ftb.mods:ftb-chunks-fabric:${project.ftb_chunks_version}"
            modImplementation "dev.architectury:architectury-fabric:${project.architectury_version}"
            break
        case "atlas":
            modLocalRuntime("maven.modrinth:map-atlases:${project.map_atlases_version_fabric}")
            modLocalRuntime("maven.modrinth:moonlight:${project.moonlight_version_fabric}")
            modLocalRuntime("dev.onyxstudios.cardinal-components-api:cardinal-components-item:${project.cardinal_components_version}")
            modLocalRuntime("dev.onyxstudios.cardinal-components-api:cardinal-components-base:${project.cardinal_components_version}")
            modLocalRuntime("dev.onyxstudios.cardinal-components-api:cardinal-components-entity:${project.cardinal_components_version}")
            break
        case "none":
            break
        default: println("Unknown minimap mod specified: ${project.minimap_mod}. Must be xaero, journey, ftb, " +
                "atlas, or none")
    }

    // Accessory Mod Dev Tests
    // See root gradle.properties to choose which to use at runtime.
    switch (project.accessory_mod.toLowerCase(Locale.ROOT)) {
        case "accessories":
            modLocalRuntime "io.wispforest:accessories-fabric:${project.accessories_version}"
            modLocalRuntime "io.wispforest:owo-lib:${project.owo_version}"
            modLocalRuntime("me.shedaniel.cloth:cloth-config-fabric:${project.cloth_config_version}") {
                exclude(group: "net.fabricmc.fabric-api")
            }
            break
        case "none":
            break
        default: println("Unknown accessory mod specified: ${project.accessory_mod}. Must be accessories, or none")
    }
}

publishMods {
    displayName = "${mod_id}-fabric-${minecraft_version}-${mod_version}"
    version = "${minecraft_version}-${mod_version}"
    modLoaders.add("fabric")
    file project(":fabric")


    curseforge("curseforgeFabric") {
        accessToken = System.getenv("CURSEFORGE_TOKEN")
        changelogType = "markdown"
        javaVersions.add(JavaVersion.toVersion(project.java_version))
        minecraftVersions.addAll(curseforge_gameVersions.split(","))
        projectId = project.curseforge_fabric_id

        requires("forge-config-api-port")
        optional("serene-seasons", "fabric-seasons", "fabric-seasons-extras")
        optional("ftb-chunks-fabric", "journeymap", "xaeros-minimap", "xaeros-minimap-fair-play-edition", "map-atlases")
        optional("trinkets", "accessories")
    }

    modrinth("modrinthFabric") {
        accessToken = System.getenv("MODRINTH_TOKEN")
        minecraftVersions.addAll(modrinth_gameVersions.split(","))
        projectId = project.modrinth_fabric_id

        requires("forge-config-api-port")
        optional("serene-seasons", "fabric-seasons", "fabric-seasons-extras")
        optional("journeymap", "xaeros-minimap", "xaeros-minimap-fair-play-edition", "map-atlases")
        optional("trinkets", "accessories")
    }
}