# Fabric Loader
- repository: https://maven.fabricmc.net
  groupId: net.fabricmc
  artifactId: fabric-loader
  version: "*"
  properties:
    fabric_loader_version:
      source: version

# Fabric API
- repository: https://maven.fabricmc.net
  groupId: net.fabricmc.fabric-api
  artifactId: fabric-api
  version: "*+${mcVersion}"
  properties:
    fabric_api_version:
      source: version

# Forge
- repository: https://maven.minecraftforge.net/
  groupId: net.minecraftforge
  artifactId: forge
  version: "${mcVersion}-*"
  properties:
    forge_version:
      source: version

# Parchment
- repository: https://maven.parchmentmc.org/
  groupId: org.parchmentmc.data
  artifactId: parchment-${mcVersion}
  version: "*"
  properties:
    parchment_version:
      source: version

# DevAuth
- repository: https://pkgs.dev.azure.com/djtheredstoner/DevAuth/_packaging/public/maven/v1
  groupId: me.djtheredstoner
  artifactId: DevAuth-fabric
  version: "*"
  properties:
    devauth_version:
      source: version

# Mod Menu
- repository: https://maven.terraformersmc.com/releases/
  groupId: com.terraformersmc
  artifactId: modmenu
  version: "3.*"
  properties:
    modmenu_version:
      source: version

# Xaero
- repository: https://chocolateminecraft.com/maven
  groupId: xaero.minimap
  artifactId: xaerominimap-common-${mcVersion}
  version: "${xaero_minimap_version}"
  properties:
    xaero_minimap_version:
      source: version

# Xaero's Lib
- repository: https://chocolateminecraft.com/maven
  groupId: xaero.lib
  artifactId: xaerolib-common-${mcVersion}
  version: "${xaero_lib_version}"
  properties:
    xaero_lib_version:
      source: version

# Journeymap-API
- repository: https://maven.blamejared.com/
  groupId: info.journeymap
  artifactId: journeymap-api
  version: "${mcVersion}-*"
  properties:
    journeymap_api_version:
      source: version

# Journeymap-Forge
- repository: https://api.modrinth.com/maven
  groupId: maven.modrinth
  artifactId: journeymap
  version: "${mcVersion}-*-forge"
  properties:
    journeymap_version_forge:
      source: version

# Journeymap-Fabric
- repository: https://api.modrinth.com/maven
  groupId: maven.modrinth
  artifactId: journeymap
  version: "${mcVersion}-*-fabric"
  properties:
    journeymap_version_fabric:
      source: version

# Architectury
- repository: https://maven.shedaniel.me
  groupId: dev.architectury
  artifactId: architectury-fabric
  version: "4.*"
  properties:
    architectury_version:
      source: version

# Moonlight Forge
- repository: https://api.modrinth.com/maven
  groupId: maven.modrinth
  artifactId: moonlight
  version: "${mcVersion}-*-forge"
  properties:
    moonlight_version_forge:
      source: version

# Moonlight Fabric
- repository: https://api.modrinth.com/maven
  groupId: maven.modrinth
  artifactId: moonlight
  version: "${mcVersion}-*-fabric"
  properties:
    moonlight_version_fabric:
      source: version