# Fabric Loader
- repository: https://maven.fabricmc.net
  groupId: net.fabricmc
  artifactId: fabric-loader
  version: "*"
  properties:
    fabric_loader_version:
      source: version

# Fabric API
- repository: https://maven.fabricmc.net
  groupId: net.fabricmc.fabric-api
  artifactId: fabric-api
  version: "*+${mcVersion}"
  properties:
    fabric_api_version:
      source: version

# Forge
- repository: https://maven.minecraftforge.net/
  groupId: net.minecraftforge
  artifactId: forge
  version: "${mcVersion}-*"
  properties:
    forge_version:
      source: version


# DevAuth
- repository: https://pkgs.dev.azure.com/djtheredstoner/DevAuth/_packaging/public/maven/v1
  groupId: me.djtheredstoner
  artifactId: DevAuth-fabric
  version: "*"
  properties:
    devauth_version:
      source: version

# Serene Seasons
- repository: https://maven.minecraftforge.net/
  groupId: com.github.glitchfiend
  artifactId: SereneSeasons-fabric
  version: "${mcVersion}-*"
  properties:
    serene_seasons_version:
      source: version

# GlitchCore
- repository: https://maven.minecraftforge.net/
  groupId: com.github.glitchfiend
  artifactId: GlitchCore-fabric
  version: "${mcVersion}-*"
  properties:
    glitchcore_version:
      source: version

# Forge Config API Port
- repository: https://raw.githubusercontent.com/Fuzss/modresources/main/maven/
  groupId: fuzs.forgeconfigapiport
  artifactId: forgeconfigapiport-fabric
  version: "8.*"
  properties:
    forge_config_api_port_version:
      source: version

# Mod Menu
- repository: https://maven.terraformersmc.com/releases/
  groupId: com.terraformersmc
  artifactId: modmenu
  version: "7.*"
  properties:
    modmenu_version:
      source: version

# Xaero
- repository: https://api.modrinth.com/maven
  groupId: maven.modrinth
  artifactId: xaeros-minimap
  version: "${xaeros_minimap_version}_Fabric_${mcVersion}"
  properties:
    xaeros_minimap_version:
      source: wildcard

# Journeymap
- repository: https://api.modrinth.com/maven
  groupId: maven.modrinth
  artifactId: journeymap
  version: "1.20.1-${journeymap_version}-fabric"
  properties:
    journeymap_version:
      source: wildcard

# FTB Chunks
- repository: https://maven.ftb.dev/releases
  groupId: dev.ftb.mods
  artifactId: ftb-chunks-fabric
  version: "2001.*"
  properties:
    ftb_chunks_version:
      source: version

# FTB Teams
- repository: https://maven.ftb.dev/releases
  groupId: dev.ftb.mods
  artifactId: ftb-teams-fabric
  version: "2001.*"
  properties:
    ftb_teams_version:
      source: version

# FTB Library
- repository: https://maven.ftb.dev/releases
  groupId: dev.ftb.mods
  artifactId: ftb-library-fabric
  version: "2001.*"
  properties:
    ftb_library_version:
      source: version

# Architectury
- repository: https://maven.shedaniel.me
  groupId: dev.architectury
  artifactId: architectury-fabric
  version: "9.*"
  properties:
    architectury_version:
      source: version