plugins {
    id 'java-library'
    id 'maven-publish'
    id 'me.modmuss50.mod-publish-plugin'
}

base {
    archivesName = "${mod_id}-${project.name}-${minecraft_version}"
}

group = project.group
version = project.mod_version

java {
    toolchain.languageVersion = JavaLanguageVersion.of(java_version)
    //withSourcesJar()
    //withJavadocJar()
}

repositories {
    mavenCentral()

    exclusiveContent {
        forRepository {
            maven {
                name = "CurseMaven"
                url = "https://cursemaven.com"
            }
        }
        filter {
            includeGroup "curse.maven"
        }
    }

    exclusiveContent {
        forRepository {
            maven {
                name = "Modrinth Maven"
                url = "https://api.modrinth.com/maven"
            }
        }
        filter {
            includeGroup "maven.modrinth"
        }
    }

    exclusiveContent {
        forRepository {
            maven {
                name = 'Sponge Maven'
                url = 'https://repo.spongepowered.org/repository/maven-public'
            }
        }
        filter { includeGroupAndSubgroups('org.spongepowered') }
    }

    maven {
        name = "Parchment Maven"
        url = "https://maven.parchmentmc.org"
        content {
            includeGroup "org.parchmentmc.data"
        }
    }

    maven {
        name = "shedaniel Maven - Cloth Config, REI, Architectury"
        url = "https://maven.shedaniel.me/"
        content {
            includeGroup "me.shedaniel"
            includeGroup "dev.architectury"
            includeGroup "me.shedaniel.cloth"
        }
    }

    maven {
        name = "LadySnake Maven - Cardinal Components"
        url = "https://maven.ladysnake.org/releases"
        content {
            includeGroup "dev.onyxstudios.cardinal-components-api"
            includeGroup "org.ladysnake.cardinal-components-api"
        }
    }
    maven {
        name = "Xaero Maven"
        url = "https://chocolateminecraft.com/maven"
        content {
            includeGroup "xaero.lib"
        }
    }

    maven {
        name = "Journeymap API MAven"
        url = "https://jm.gserv.me/repository/maven-public/"
        content {
            includeGroup "info.journeymap"
        }
    }

    maven {
        name = "Curios Maven"
        url = "https://maven.theillusivec4.top/"
        content {
            includeGroup "top.theillusivec4.curios"
        }
    }
    // Mod Menu, Trinkets
    maven {
        name = "TerraformerMC Maven"
        url = "https://maven.terraformersmc.com/releases/"
        content {
            includeGroup "com.terraformersmc"
            includeGroup "dev.emi"
        }
    }

    maven {
        name = "Accessories Maven"
        url = "https://maven.wispforest.io/releases"
        content {
            includeGroup "io.wispforest"
            includeGroup "io.wispforest.endec"
        }
    }
    // Accessories Dependencies
    maven {
        name = "Sinytra Maven"
        url = "https://maven.su5ed.dev/releases"
        content {
            includeGroup "dev.su5ed.sinytra.fabric-api"
        }
    }

    maven {
        name = "Forge Config API Port Maven"
        url = "https://raw.githubusercontent.com/Fuzss/modresources/main/maven/"
        content {
            includeGroup "fuzs.forgeconfigapiport"
        }
    }

    maven {
        name = "DevAuth Maven"
        url = "https://pkgs.dev.azure.com/djtheredstoner/DevAuth/_packaging/public/maven/v1"
        content {
            includeGroup "me.djtheredstoner"
        }
    }

    maven {
        name = "FTB Maven"
        url = "https://maven.ftb.dev/releases"
        content {
            includeGroup "dev.ftb.mods"
        }
    }

    maven {
        name = "Forge Maven"
        url = "https://maven.minecraftforge.net"
    }

    maven {
        name = "ModMaven (Backup)"
        url = "https://modmaven.dev/"
    }
}

dependencies {
    implementation 'com.demonwav.mcdev:annotations:2.1.0'
}

// Declare capabilities on the outgoing configurations.
// Read more about capabilities here: https://docs.gradle.org/current/userguide/component_capabilities.html#sec:declaring-additional-capabilities-for-a-local-component
//['apiElements', 'runtimeElements', 'sourcesElements', 'javadocElements'].each { variant ->
['apiElements', 'runtimeElements'].each { variant ->
    configurations."$variant".outgoing {
        capability("$group:${project.name}:$version")
        capability("$group:${base.archivesName.get()}:$version")
        capability("$group:$mod_id-${project.name}-${minecraft_version}:$version")
        capability("$group:$mod_id:$version")
    }
    publishing.publications.configureEach {
        suppressPomMetadataWarningsFor(variant)
    }
}

//sourcesJar {
//    from(rootProject.file('LICENSE')) {
//        rename { "${it}_${mod_name}" }
//    }
//}

jar {
    from(rootProject.file('LICENSE')) {
        rename { "${it}_${mod_name}" }
    }

    manifest {
        attributes([
                'Specification-Title'   : mod_name,
                'Specification-Vendor'  : mod_author,
                'Specification-Version' : project.jar.archiveVersion,
                'Implementation-Title'  : project.name,
                'Implementation-Version': project.jar.archiveVersion,
                'Implementation-Vendor' : mod_author,
                'Built-On-Minecraft'    : minecraft_version
        ])
    }
}

processResources {
    def expandProps = [
            "version"                   : project.version,
            "group"                     : project.group, //Else we target the task's group.
            "minecraft_version"         : minecraft_version,
            "forge_version"             : forge_version,
            "forge_loader_version_range": forge_loader_version_range,
            "forge_version_range"       : forge_version_range,
            "minecraft_version_range"   : minecraft_version_range,
            "fabric_api_version"        : fabric_api_version,
            "fabric_loader_version"     : fabric_loader_version,
            "fabric_version_range"      : fabric_version_range,
            "mod_name"                  : mod_name,
            "mod_author"                : mod_author,
            "mod_id"                    : mod_id,
            "license"                   : license,
            "description"               : project.description,
            "repoURL"                   : repoURL,
            "issueTrackerURL"           : issueTrackerURL,
            "credits"                   : credits,
            "java_version"              : java_version
    ]

    var jsonExpandProps = expandProps.collectEntries {
        key, value -> [(key): value instanceof String ? value.replace("\n", "\\\\n") : value]
    }

    filesMatching(['META-INF/mods.toml']) {
        expand expandProps
    }

    filesMatching(['pack.mcmeta', 'fabric.mod.json', '*.mixins.json']) {
        expand jsonExpandProps
    }

    inputs.properties(expandProps)
}

publishing {
    publications {
        register('mavenJava', MavenPublication) {
            artifactId base.archivesName.get()
            from components.java
        }
    }
    repositories {
        maven {
            url System.getenv('local_maven_url')
        }
    }
}

tasks.register('latestChangelog') {
    group = "changelog"

    def fullChangelog = projectDir.toPath().getParent().resolve("CHANGELOG.md").toFile()
    def latestChangelog = projectDir.toPath().getParent().resolve("LATEST_CHANGELOG.md").toFile()

    int firstHeading = fullChangelog.getText().indexOf("## [")
    int nextHeading = fullChangelog.getText().indexOf("## [", firstHeading + 1)

    String latestChangelogText = fullChangelog.getText().substring(firstHeading, nextHeading)

    outputs.upToDateWhen {
        if (latestChangelog.exists()) {
            return latestChangelogText == latestChangelog.getText()
        } else return false
    }

    outputs.file file("LATEST_CHANGELOG.md")
    doLast {
        latestChangelog.text = latestChangelogText
        printf(latestChangelog.text)
    }
}

publishMods {
    var mcVer = minecraft_version.split("\\.").toList()
    int mcMajor
    int mcMinor
    if (mcVer.get(0).toInteger() == 1) {
        mcMajor = mcVer.get(1).toInteger()
        mcMinor = mcVer.get(2).toInteger()
    } else {
        mcMajor = mcVer.get(0).toInteger()
        mcMinor = mcVer.get(1).toInteger()
    }

    dryRun = true
    type = STABLE
    changelog = projectDir.toPath().getParent().resolve("LATEST_CHANGELOG.md").getText()

    def cfOptions = curseforgeOptions {
        accessToken = System.getenv("CURSEFORGE_TOKEN")
        changelogType = "markdown"
        javaVersions.add(JavaVersion.toVersion(project.java_version))
        version = "${minecraft_version}-${mod_version}"
        minecraftVersions.addAll(curseforge_gameVersions.split(","))
    }

    def mrOptions = modrinthOptions {
        accessToken = System.getenv("MODRINTH_TOKEN")
        minecraftVersions.addAll(modrinth_gameVersions.split(","))
    }

    curseforge("curseforgeFabric") {
        from cfOptions
        projectId = project.curseforge_fabric_id
        file project(":fabric")
        displayName = "${mod_id}-fabric-${minecraft_version}-${mod_version}"
        modLoaders.add("fabric")
        requires("forge-config-api-port")
        optional("serene-seasons", "fabric-seasons", "fabric-seasons-extras")
        optional("ftb-chunks-fabric", "journeymap", "xaeros-minimap", "xaeros-minimap-fair-play-edition", "map-atlases")
        optional("trinkets", "accessories")
    }

    curseforge("curseforgeForge") {
        from cfOptions
        projectId = project.curseforge_forge_id
        file project(":forge")
        displayName = "${mod_id}-forge-${minecraft_version}-${mod_version}" + mcMajor + mcMinor
        modLoaders.add("forge")
        if (minecraft_version == "1.20.1") {
            modLoaders.add("neoforge")
        }
        optional("serene-seasons", "terrafirmacraft", "ecliptic-seasons")
        optional("ftb-chunks-forge", "journeymap", "xaeros-minimap", "xaeros-minimap-fair-play-edition", "map-atlases-forge")
        optional("curios", "accessories")
    }

    if (mcMajor >= 21) {
        curseforge("curseforgeNeoForge") {
            from cfOptions
            projectId = project.curseforge_forge_id
            file project(":neoforge")
            displayName = "${mod_id}-neoforge-${minecraft_version}-${mod_version}"
            modLoaders.add("neoforge")
            optional("serene-seasons", "terrafirmacraft", "ecliptic-seasons")
            optional("ftb-chunks-forge", "journeymap", "xaeros-minimap", "xaeros-minimap-fair-play-edition", "map-atlases-forge")
            optional("curios", "accessories")
        }
    }
}

tasks.register('publishAll') {
    group = "upload"

    dependsOn("latestChangelog")
    dependsOn("publishMods")
}