# Gradle
org.gradle.jvmargs=-Xmx4G
org.gradle.parallel=true
org.gradle.configuration-cache=false
enabled_platforms=fabric,forge

# Mappings
# https://parchmentmc.org/docs/getting-started
parchment_version=2023.09.03
parchment_minecraft=1.20.1

# Project
license=MIT
credits=IanAnderson
repoURL=https://github.com/IanMods/SeasonHUD
issueTrackerURL=https://github.com/IanMods/SeasonHUD/issues

# Mod options
mod_version=2.0.1
mod_id=seasonhud
mod_group=club.iananderson
mod_name=SeasonHud
mod_author=IanAnderson
mod_description=Client-side addon that displays the current season on the HUD, or under various minimap mods.

# Minecraft properties
minecraft_version=1.20.1
minecraft_version_range=[1.20, 1.20.2)
java_version=17

# Curseforge/Modrinth
modrinth_forge_id=VNjUn3NA
modrinth_fabric_id=iDiIfZLX
modrinth_gameVersions=1.20,1.20.1
curseforge_forge_id=690971
curseforge_fabric_id=848022
curseforge_gameVersions=1.20,1.20.1

# Forge properties
# https://files.minecraftforge.net/net/minecraftforge/forge/index_1.20.1.html
forge_version=1.20.1-47.4.16
forge_version_range=[46,)
forge_loader_version_range=[46,)

# Fabric properties
# https://fabricmc.net/develop/
fabric_loader_version=0.18.4
fabric_api_version=0.92.7+1.20.1
fabric_version_range=>=1.20 <=1.20.1

# Neoforge properties
# https://projects.neoforged.net/neoforged/neoforge
neoforge_version=21.1.219
neoforge_version_range=[21.0,)
neoforge_loader_version_range=[4,)

# Mixins
mixin_version=0.8.5
mixin_extras_version=0.4.1

# ForgeConfigApiPort properties
# https://modrinth.com/mod/forge-config-api-port/versions?g=1.20.1&l=fabric
forge_config_api_port_version=8.0.3

# Season Mods
# https://modrinth.com/mod/serene-seasons/versions?g=1.20.1&l=forge
# https://modrinth.com/mod/glitchcore/versions?g=1.20.1&l=forge
# https://modrinth.com/mod/fabric-seasons/versions?g=1.20.1&l=fabric
# https://modrinth.com/mod/fabric-seasons-extras/versions?g=1.20.1&l=fabric
# https://modrinth.com/mod/terrafirmacraft/versions?g=1.20.1&l=forge
# https://modrinth.com/mod/patchouli/versions?g=1.20.1&l=forge
# https://modrinth.com/mod/barrels-2012/versions?g=1.20.1&l=forge
# https://www.curseforge.com/minecraft/mc-mods/ecliptic-seasons/files/all?page=1&pageSize=20&version=1.20.1&gameVersionTypeId=1
serene_seasons_version=1.20.1-9.1.0.2
glitchcore_version=1.20.1-0.0.1.1
fabric_seasons_version=2.4.2-BETA+1.20
fabric_seasons_extras_version=1.3.2-BETA+1.20
terrafirmacraft_version=3.2.20
patchouli_version=1.20.1-84.1-forge
barrels_version=2.1
ecliptic_seasons_version=7014423
homeostatic_seasons_version=1.1.0.4
homeostatic_seasons_mc_version=1.21.1
whitenoise_version=2.0.7
climatesettings_version=1.2.0
protomanlys_version=0.16.4-alpha

# Minimaps - Common
# https://modrinth.com/mod/xaeros-minimap/versions?g=1.20.1&l=neoforge&l=fabric
# https://modrinth.com/mod/journeymap/versions?g=1.20.1&l=neoforge&l=fabric
# https://github.com/TeamJM/journeymap-api/tree/1.20.1_2.0_SNAPSHOTS
# https://modrinth.com/mod/common-network/versions?g=1.20.1&l=neoforge&l=fabric
# https://modrinth.com/mod/architectury-api/versions?g=1.20.1&l=neoforge&l=fabric
# https://modrinth.com/mod/map-atlases-forge/versions?g=1.20.1&g=1.20.1&l=forge
# https://modrinth.com/mod/map-atlases/versions?g=1.20.1&g=1.20.1&l=fabric
# https://modrinth.com/mod/moonlight/versions?g=1.20.1&l=forge&l=fabric
# https://modrinth.com/mod/immediatelyfast/versions?g=1.20.1&l=forge&l=fabric
# https://www.curseforge.com/minecraft/mc-mods/ftb-library-fabric/files/all?page=1&pageSize=20&version=1.20.1
# https://www.curseforge.com/minecraft/mc-mods/ftb-teams-fabric/files/all?page=1&pageSize=20&version=1.20.1
# https://www.curseforge.com/minecraft/mc-mods/ftb-chunks-fabric/files/all?page=1&pageSize=20&version=1.20.1
xaero_minimap_version=25.3.10
xaero_lib_version=1.1.0
xaero_mc_version=1.20
journeymap_version_fabric=1.20.1-5.10.3-fabric
journeymap_version_forge=1.20.1-5.10.3-forge
journeymap_api_version=1.20-1.9
architectury_version=9.2.14
map_atlases_version=1.20-6.0.19
moonlight_version_forge=1.20-2.16.28-forge
moonlight_version_fabric=1.20-2.16.28-fabric
ftb_library_version=2001.2.12
ftb_teams_version=2001.3.2
ftb_chunks_version=2001.3.6

# Curios/Trinkets/Accessories
# https://modrinth.com/mod/curios/versions?g=1.20.1&l=forge
# https://modrinth.com/mod/trinkets/versions?g=1.20.1&l=fabric
# https://modrinth.com/mod/accessories/versions?g=1.20.1&l=fabric
# https://modrinth.com/mod/owo-lib/versions?g=1.20.1
curios_version=5.14.1+1.20.1
trinkets_version=3.7.2
accessories_version=1.0.0-beta.47+1.20.1
owo_version=0.11.2+1.20
owo_version_neoforge=
endec_version=0.1.8
endec_gson_version=0.1.5
endec_jankson_version=0.1.3.1
endec_netty_version=0.1.4

# Development QOL
# Mod Menu - https://modrinth.com/mod/modmenu/versions?g=1.20.1&l=fabric
# LazyDFU - https://modrinth.com/mod/lazydfu/versions?g=1.20.1&l=fabric
# Cloth Config - https://modrinth.com/mod/cloth-config/versions?g=1.20.1&l=fabric
# Text Animator - https://modrinth.com/mod/text-animator/versions?g=1.20.1
cardinal_components_version=5.2.1
modmenu_version=7.2.2
lazydfu_version=0.1.3
cloth_config_version=11.1.136
devauth_version=1.2.2

# Dev season mod
# Forge Options: serene, terra, ecliptic
# NeoForge Options: serene, terra, ecliptic
# Fabric Options: serene, fabric, fabric+extra
season_mod_neoforge=serene
season_mod_forge=serene
season_mod_fabric=fabric+extra

# Dev minimap mod
# Options: xaero, journey, ftb, atlas, none
minimap_mod=journey

# Dev accessory mod
# Options: accessories, none
accessory_mod=none