# Gradle
org.gradle.jvmargs=-Xmx4G
org.gradle.parallel=true
org.gradle.configuration-cache=false
net.minecraftforge.gradle.merge-source-sets=true
enabled_platforms=fabric,forge,neoforge

# Mappings
# https://parchmentmc.org/docs/getting-started
parchment_version=2025.09.14
parchment_minecraft=1.21.8

# Project
license=MIT
credits=IanAnderson
repoURL=https://github.com/IanMods/SeasonHUD
issueTrackerURL=https://github.com/IanMods/SeasonHUD/issues

# Mod options
mod_version=2.0.2
mod_id=seasonhud
mod_group=club.iananderson
mod_name=SeasonHud
mod_author=IanAnderson
mod_description=Client-side addon that displays the current season on the HUD, or under various minimap mods.

# Minecraft properties
minecraft_version=1.21.8
minecraft_version_range=[1.21.6, 1.21.9)
java_version=21

# Curseforge/Modrinth
modrinth_forge_id=VNjUn3NA
modrinth_fabric_id=iDiIfZLX
modrinth_gameVersions=1.21.6,1.21.7,1.21.8
curseforge_forge_id=690971
curseforge_fabric_id=848022
curseforge_gameVersions=1.21.6,1.21.7,1.21.8

# Forge properties
# https://files.minecraftforge.net/net/minecraftforge/forge/index_1.21.8.html
forge_version=1.21.8-58.1.11
forge_version_range=[51,)
forge_loader_version_range=[51,)

# Fabric properties
# https://fabricmc.net/develop/
fabric_loader_version=0.18.4
fabric_api_version=0.136.1+1.21.8
fabric_version_range=~1.21

# Neoforge properties
# https://projects.neoforged.net/neoforged/neoforge
neoforge_version=21.8.52
neoforge_version_range=[21.0,)
neoforge_loader_version_range=[4,)

# This is the version of minecraft that the 'common' project uses, you can find a list of all versions here
# https://projects.neoforged.net/neoforged/neoform
neo_form_version=1.21.8-20250717.133445

# Mixins
mixin_version=0.8.5
mixin_extras_version=0.5.0

# ForgeConfigApiPort properties
# https://modrinth.com/mod/forge-config-api-port/versions?g=1.21.8&l=fabric
forge_config_api_port_version=21.8.2

# Season Mods
# https://modrinth.com/mod/serene-seasons/versions?g=1.21.8&l=forge
# https://modrinth.com/mod/glitchcore/versions?g=1.21.8&l=forge
# https://modrinth.com/mod/fabric-seasons/versions?g=1.21.8&l=fabric
# https://modrinth.com/mod/fabric-seasons-extras/versions?g=1.21.8&l=fabric
# https://modrinth.com/mod/terrafirmacraft/versions?g=1.21.8&l=neoforge
# https://modrinth.com/mod/patchouli/versions?g=1.21.8&l=neoforge
# https://modrinth.com/mod/barrels-2012/versions?g=1.21.8&l=neoforge
# https://www.curseforge.com/minecraft/mc-mods/ecliptic-seasons/files/all?page=1&pageSize=20&version=1.21.1&gameVersionTypeId=6
serene_seasons_version=1.21.8-21.8.0.0
glitchcore_version=1.21.8-21.8.0.0
fabric_seasons_version=2.4.2-BETA+1.21
fabric_seasons_extras_version=1.3.2-BETA+1.21
terrafirmacraft_version=4.0.19-beta
patchouli_version=1.21.1-92-neoforge
barrels_version=2.1
ecliptic_seasons_version=7595115
homeostatic_seasons_mc_version=1.21.1
homeostatic_seasons_version=1.1.0.4
homeostatic_seasons_mc_version=1.21.1
whitenoise_version=2.0.7
climatesettings_version=1.2.0
protomanlys_version=0.16.4-alpha

# Minimaps - Common
# https://modrinth.com/mod/xaeros-minimap/versions?g=1.21.8&l=neoforge&l=fabric
# https://modrinth.com/mod/journeymap/versions?g=1.21.8&l=neoforge&l=fabric
# https://github.com/TeamJM/journeymap-api/tree/1.21.1_2.0_SNAPSHOTS
# https://modrinth.com/mod/common-network/versions?g=1.21.8&l=neoforge&l=fabric
# https://modrinth.com/mod/architectury-api/versions?g=1.21.8&l=neoforge&l=fabric
# https://modrinth.com/mod/map-atlases-forge/versions?g=1.21.8&l=neoforge
# https://modrinth.com/mod/map-atlases/versions?g=1.21.8&l=fabric
# https://modrinth.com/mod/moonlight/versions?g=1.21.8&l=neoforge&l=fabric
# https://modrinth.com/mod/immediatelyfast/versions?g=1.21.8&l=neoforge&l=fabric
# https://www.curseforge.com/minecraft/mc-mods/ftb-chunks-fabric/files/all?page=1&pageSize=20&version=1.21.8
# https://www.curseforge.com/minecraft/mc-mods/ftb-library-fabric/files/all?page=1&pageSize=20&version=1.21.8
# https://www.curseforge.com/minecraft/mc-mods/ftb-teams-fabric/files/all?page=1&pageSize=20&version=1.21.8
xaero_minimap_version=25.3.10
xaero_lib_version=1.1.0
xaero_mc_version=1.21.8
journeymap_version_fabric=1.21.8-6.0.0-beta.52+fabric
journeymap_version_forge=1.21.8-6.0.0-beta.52+forge
journeymap_version_neoforge=1.21.8-6.0.0-beta.52+neoforge
journeymap_api_version=2.0.0-1.21.7
common_network_version=1.0.21-1.21.7
architectury_version=16.1.4
map_atlases_version_forge=1.21-6.5.0-neoforge
map_atlases_version_neoforge=1.21-6.5.0-neoforge
map_atlases_version_fabric=1.21-6.5.0-fabric
moonlight_version_forge=1.21-2.29.16-neoforge
moonlight_version_neoforge=1.21-2.29.16-neoforge
moonlight_version_fabric=1.21-2.29.16-fabric
ftb_library_version=2101.1.30
ftb_teams_version=2101.1.9
ftb_chunks_version=2101.1.14

#Curios/Trinkets/Accessories
# https://modrinth.com/mod/curios/versions?g=1.21.8&l=neoforge
# https://modrinth.com/mod/trinkets/versions?g=1.21.8&l=fabric
# https://modrinth.com/mod/accessories/versions?g=1.21.8&l=fabric
# https://modrinth.com/mod/owo-lib/versions?g=1.21.1
curios_version=12.0.0+1.21.8
trinkets_version=3.10.0
accessories_version=1.3.8-beta+1.21.8
owo_version=0.12.23+1.21.8
owo_version_neoforge=0.12.25+1.21.8
endec_version=0.1.8
endec_gson_version=0.1.5
endec_jankson_version=0.1.3.1
endec_netty_version=0.1.4

# Development QOL
cardinal_components_version=6.0.0
modmenu_version=15.0.0
lazydfu_version=
cloth_config_version=19.0.147
devauth_version=1.2.2
sodium_version_fabric=mc1.21.8-0.7.3-fabric
sodium_version_neoforge=mc1.21.8-0.7.3-neoforge

# NeoForge Options: serene, terra, ecliptic, homeostatic, protomanlys
# Forge Options: serene, terra, ecliptic
# Fabric Options: serene, fabric, fabric+extra, homeostatic
season_mod_neoforge=serene
season_mod_forge=serene
season_mod_fabric=serene

# Dev minimap mod
# Options: xaero, journey, ftb, atlas, none
minimap_mod=xaero

# Dev accessory mod
# Options: accessories, none
accessory_mod=none