import net.darkhax.curseforgegradle.TaskPublishCurseForge

plugins {
    id 'multiloader-loader'
    id 'net.neoforged.moddev.legacyforge'
    id 'net.darkhax.curseforgegradle'
    id "com.modrinth.minotaur"
}

mixin {
    add(sourceSets.main, "${mod_id}.refmap.json")

    config("${mod_id}.mixins.json")

    if (project(":forge").file("src/main/resources/${mod_id}.forge.mixins.json").exists()) {
        config("${mod_id}.forge.mixins.json")
    }
}

legacyForge {
    version = forge_version

    validateAccessTransformers = true

    def at = project(':common').file('src/main/resources/META-INF/accesstransformer.cfg')
    if (at.exists()) {
        accessTransformers = ["src/main/resources/META-INF/accesstransformer.cfg"]
    }
    parchment {
        minecraftVersion = parchment_minecraft
        mappingsVersion = parchment_version
    }
    runs {
        client {
            client()
        }
        data {
            data()
            programArguments.addAll '--mod', project.mod_id, '--all', '--output', file('src/generated/resources/').getAbsolutePath(), '--existing', file('src/main/resources/').getAbsolutePath()
        }
        server {
            server()
        }
    }

    mods {
        "${mod_id}" {
            sourceSet sourceSets.main
            sourceSet project(":common").sourceSets.main
        }
    }
}

sourceSets.main.resources.srcDir 'src/generated/resources'


dependencies {
    compileOnly project(":common")
    annotationProcessor("org.spongepowered:mixin:${project.mixin_version}:processor")

    // Serene Seasons
    modCompileOnly "com.github.glitchfiend:SereneSeasons-forge:${project.serene_seasons_version}"
    modCompileOnly "com.github.glitchfiend:GlitchCore-forge:${project.glitchcore_version}"
    compileOnly("net.jodah:typetools:0.6.3")

    // Terrafirmacraft
    modCompileOnly "maven.modrinth:terrafirmacraft:${project.terrafirmacraft_version}"
    modCompileOnly "maven.modrinth:patchouli:${project.patchouli_version}-forge"
    modCompileOnly "maven.modrinth:barrels-2012:${project.barrels_version}"

    // Ecliptic Seasons
    modCompileOnly "curse.maven:ecliptic-seasons-1118306:${project.ecliptic_seasons_version}"

    // Xaero's Minimap
    modCompileOnly "maven.modrinth:xaeros-minimap:${project.xaeros_minimap_version}_Forge_${project.xaero_mc_version}"
    modCompileOnly "xaero.lib:xaerolib-forge-${project.xaero_mc_version}:${project.xaero_lib_version}"

    // JourneyMap
    modCompileOnly "maven.modrinth:journeymap:${project.journeymap_version_forge}"

    //FTB Chunks + Dependencies
    modCompileOnly "dev.ftb.mods:ftb-library-forge:${project.ftb_library_version}"
    modCompileOnly "dev.ftb.mods:ftb-teams-forge:${project.ftb_teams_version}"
    modCompileOnly "dev.ftb.mods:ftb-chunks-forge:${project.ftb_chunks_version}"
    modCompileOnly "maven.modrinth:architectury-api:${project.architectury_version}+forge"

    // Map Atlases
    modCompileOnly "maven.modrinth:map-atlases-forge:${project.map_atlases_version}"
    modCompileOnly "maven.modrinth:moonlight:${project.moonlight_version_forge}"

    // Curios
    modCompileOnly "top.theillusivec4.curios:curios-forge:${project.curios_version}"
    modCompileOnly "top.theillusivec4.curios:curios-forge:${project.curios_version}:api"

    // Accessories
    modCompileOnly "io.wispforest:accessories-neoforge:${project.accessories_version}"
    modCompileOnly "me.shedaniel.cloth:cloth-config-forge:${project.cloth_config_version}"

    // Development QOL
    implementation("me.djtheredstoner:DevAuth-forge-latest:${devauth_version}")
    // implementation("maven.modrinth:text-animator:${project.text_animator_version_forge}")

    // Minimap Mod Dev Tests
    // See root gradle.properties to choose which to use at runtime.
    switch (project.minimap_mod.toLowerCase(Locale.ROOT)) {
        case "xaero":
            modImplementation "maven.modrinth:xaeros-minimap:${project.xaeros_minimap_version}_Forge_${project.xaero_mc_version}"
            modImplementation "xaero.lib:xaerolib-forge-${project.xaero_mc_version}:${project.xaero_lib_version}"
            break
        case "journey":
            modImplementation "maven.modrinth:journeymap:${project.journeymap_version_forge}"
            break
        case "ftb":
            modImplementation "dev.ftb.mods:ftb-library-forge:${project.ftb_library_version}"
            modImplementation "dev.ftb.mods:ftb-teams-forge:${project.ftb_teams_version}"
            modImplementation "dev.ftb.mods:ftb-chunks-forge:${project.ftb_chunks_version}"
            implementation "maven.modrinth:architectury-api:${project.architectury_version}+forge"
            compileOnly(annotationProcessor("io.github.llamalad7:mixinextras-common:0.4.1"))
            implementation("io.github.llamalad7:mixinextras-forge:0.4.1")
            break
        case "atlas":
            modImplementation "maven.modrinth:map-atlases-forge:${project.map_atlases_version}"
            modImplementation "maven.modrinth:moonlight:${project.moonlight_version_forge}"
            break
        case "none":
            break
        default: println("Unknown minimap mod specified: ${project.minimap_mod}. Must be xaero, journey, ftb, " +
                "atlas, or none")
    }

    // Accessory Mod Dev Tests
    // See root gradle.properties to choose which to use at runtime.
    switch (project.accessory_mod.toLowerCase(Locale.ROOT)) {
        case "accessories":
            implementation("io.github.llamalad7:mixinextras-forge:0.3.5")
            modImplementation("io.wispforest:accessories-neoforge:${project.accessories_version}")
            modImplementation("me.shedaniel.cloth:cloth-config-forge:${project.cloth_config_version}") {
                exclude(group: "fabric-api")
            }

            modApi("dev.su5ed.sinytra.fabric-api:fabric-api-base:0.4.31+ef105b4977") {
                exclude group: "dev.su5ed.sinytra.fabric-api"
            }
            modApi("dev.su5ed.sinytra.fabric-api:fabric-data-attachment-api-v1:1.0.0+30ef839e77") {
                exclude group: "dev.su5ed.sinytra.fabric-api"
            }
            modApi("dev.su5ed.sinytra.fabric-api:fabric-entity-events-v1:1.6.0+6274ab9d77") {
                exclude group: "dev.su5ed.sinytra.fabric-api"
            }
            modApi("dev.su5ed.sinytra.fabric-api:fabric-object-builder-api-v1:11.1.3+2174fc8477") {
                exclude group: "dev.su5ed.sinytra.fabric-api"
            }

            forgeRuntimeLibrary("io.wispforest:endec:${project.endec_version}")
            forgeRuntimeLibrary("io.wispforest.endec:gson:${project.endec_gson_version}")
            forgeRuntimeLibrary("io.wispforest.endec:netty:${project.endec_netty_version}")
            break
        case "none":
            break
        default: println("Unknown accessory mod specified: ${project.accessory_mod}. Must be accessories, or none")
    }

    // Season Mod Dev Tests (Forge)
    // See root gradle.properties to choose which to use at runtime.
    switch (project.season_mod_forge.toLowerCase(Locale.ROOT)) {
        case "serene":
            modImplementation "com.github.glitchfiend:SereneSeasons-forge:${project.serene_seasons_version}"
            modImplementation "com.github.glitchfiend:GlitchCore-forge:${project.glitchcore_version}"
            implementation("net.jodah:typetools:0.6.3")
            break
        case "terra":
            modImplementation "maven.modrinth:terrafirmacraft:${project.terrafirmacraft_version}"
            modImplementation "maven.modrinth:patchouli:${project.patchouli_version}-forge"
            modImplementation "maven.modrinth:curios:${project.curios_version}"
            modImplementation "maven.modrinth:barrels-2012:${project.barrels_version}"
            break
        case "ecliptic":
            modImplementation "curse.maven:ecliptic-seasons-1118306:${project.ecliptic_seasons_version}"
            break
        default: println("Unknown season mod specified: ${project.season_mod_forge}. Must be serene, terra, or ecliptic")
    }
}

jar {
    finalizedBy('reobfJar')

    if (project(":forge").file("src/main/resources/${mod_id}.forge.mixins.json").exists()) {
        manifest.attributes([
                "MixinConfigs": "${mod_id}.mixins.json,${mod_id}.forge.mixins.json"
        ])
    } else {
        manifest.attributes([
                "MixinConfigs": "${mod_id}.mixins.json"
        ])
    }
}


modrinth {
    debugMode = true
    token = System.getenv("MODRINTH_TOKEN")
    projectId = modrinth_forge_id
    versionNumber = minecraft_version + "-" + version
    versionName = base.archivesName.get() + "-" + mod_version
    versionType = "release"
    uploadFile = jar

    List<String> mcVersions = modrinth_gameVersions.split(",")
    gameVersions = mcVersions
    loaders = ["forge", "neoforge"]

    changelog = projectDir.toPath().getParent().resolve("LATEST_CHANGELOG.md").getText()

    dependencies {
        optional.project "serene-seasons"
        optional.project "terrafirmacraft"
        optional.project "curios"
        optional.project "accessories"
        optional.project "journeymap"
        optional.project "xaeros-minimap"
        optional.project "xaeros-minimap-fair"
        optional.project "map-atlases"
    }
}

tasks.register('publishCurseForge', TaskPublishCurseForge) {
    group = "curseforge"

    debugMode = true
    disableVersionDetection()
    apiToken = System.getenv("CURSEFORGE_TOKEN")

    def mainFile = upload(curseforge_forge_id, jar)
    mainFile.changelogType = "markdown"
    mainFile.changelog = projectDir.toPath().getParent().resolve("LATEST_CHANGELOG.md").getText()
    mainFile.releaseType = "release"

    List<String> mcVersions = curseforge_gameVersions.split(",")
    mainFile.gameVersions = mcVersions
    mainFile.addGameVersion("Forge")
    mainFile.addGameVersion("NeoForge")
    mainFile.addJavaVersion("Java 17")

    mainFile.addOptional("serene-seasons")
    mainFile.addOptional("terrafirmacraft")
    mainFile.addOptional("ecliptic-seasons")
    mainFile.addOptional("curios")
    mainFile.addOptional("accessories")
    mainFile.addOptional("ftb-chunks-forge")
    mainFile.addOptional("journeymap")
    mainFile.addOptional("xaeros-minimap")
    mainFile.addOptional("xaeros-minimap-fair-play-edition")
    mainFile.addOptional("map-atlases-forge")
}

publishMods {
    var mcVer = minecraft_version.split("\\.").toList()
    int mcMajor
    int mcMinor
    if (mcVer.get(0).toInteger() == 1) {
        mcMajor = mcVer.get(1).toInteger()
        mcMinor = mcVer.get(2).toInteger()
    } else {
        mcMajor = mcVer.get(0).toInteger()
        mcMinor = mcVer.get(1).toInteger()
    }

    displayName = "${mod_id}-forge-${minecraft_version}-${mod_version}"
    version = "${minecraft_version}-${mod_version}"
    file project(":forge")

    def cfOptions = curseforgeOptions {
        accessToken = System.getenv("CURSEFORGE_TOKEN")
        changelogType = "markdown"
        javaVersions.add(JavaVersion.toVersion(project.java_version))
        minecraftVersions.addAll(curseforge_gameVersions.split(","))
        projectId = project.curseforge_forge_id
    }

    def mrOptions = modrinthOptions {
        accessToken = System.getenv("MODRINTH_TOKEN")
        minecraftVersions.addAll(modrinth_gameVersions.split(","))
        projectId = project.modrinth_forge_id
    }

    curseforge("curseforgeForge") {
        from cfOptions
        modLoaders.add("forge")

        if (minecraft_version == "1.20.1") {
            modLoaders.add("neoforge")
        }
        optional("serene-seasons", "terrafirmacraft", "ecliptic-seasons")
        optional("ftb-chunks-forge", "journeymap", "xaeros-minimap", "xaeros-minimap-fair-play-edition", "map-atlases-forge")
        optional("curios", "accessories")
    }

    modrinth("modrinthForge") {
        from mrOptions
        modLoaders.add("forge")

        if (minecraft_version == "1.20.1") {
            modLoaders.add("neoforge")
        }
        optional("serene-seasons", "terrafirmacraft", "ecliptic-seasons")
        optional("journeymap", "xaeros-minimap", "xaeros-minimap-fair-play-edition", "map-atlases-forge")
        optional("curios", "accessories")
    }

    if (mcMajor >= 21) {
        curseforge("curseforgeNeoForge") {
            from cfOptions
            file project(":neoforge")
            displayName = "${mod_id}-neoforge-${minecraft_version}-${mod_version}"
            modLoaders.add("neoforge")
            optional("serene-seasons", "terrafirmacraft", "ecliptic-seasons")
            optional("ftb-chunks-forge", "journeymap", "xaeros-minimap", "xaeros-minimap-fair-play-edition", "map-atlases-forge")
            optional("curios", "accessories")
        }

        modrinth("modrinthNeoForge") {
            from mrOptions
            file project(":neoforge")
            displayName = "${mod_id}-neoforge-${minecraft_version}-${mod_version}"
            modLoaders.add("neoforge")
            optional("serene-seasons", "terrafirmacraft", "ecliptic-seasons")
            optional("journeymap", "xaeros-minimap", "xaeros-minimap-fair-play-edition", "map-atlases-forge")
            optional("curios", "accessories")
        }
    }


}

tasks.register('publishForge') {
    group = "upload"
    dependsOn(tasks.publishCurseForge)
    dependsOn(tasks.modrinth)
}