plugins {
    id 'multiloader-loader'
    id 'net.minecraftforge.gradle' version '[7.0.2,8.0)'
    id 'net.minecraftforge.jarjar' version '0.2.3'
}

base {
    archivesName = "${mod_name}-forge-${minecraft_version}"
}

//mixin {
//    add(sourceSets.main, "${mod_id}.refmap.json")
//
//    config("${mod_id}.mixins.json")
//
//    if (project(":forge").file("src/main/resources/${mod_id}.forge.mixins.json").exists()) {
//        config("${mod_id}.forge.mixins.json")
//    }
//}

jar {
    manifest {
        attributes["MixinConfigs"] = "${mod_id}.mixins.json,${mod_id}.forge.mixins.json"
    }
}

minecraft {
    mappings channel: 'parchment', version: parchment_version - parchment_minecraft

    // Automatically enable forge AccessTransformers if the file exists
    // This location is hardcoded in Forge and can not be changed.
    // https://github.com/MinecraftForge/MinecraftForge/blob/be1698bb1554f9c8fa2f58e32b9ab70bc4385e60/fmlloader/src/main/java/net/minecraftforge/fml/loading/moddiscovery/ModFile.java#L123
    // Forge still uses SRG names during compile time, so we cannot use the common AT's
    def at = file('src/main/resources/META-INF/accesstransformer.cfg')
    if (at.exists()) {
        accessTransformer = at
    }

    runs {
        configureEach {
            workingDir.convention layout.projectDirectory.dir('run')
            // Mixin requires either specifying the config via command line, or in the Manifest
            args "--mixin.config=${mod_id}.mixins.json"
            if (project(":forge").file("src/main/resources/${mod_id}.forge.mixins.json").exists()) {
                args "--mixin.config=${mod_id}.forge.mixins.json"
            }
        }

        client {
            var clientDir = "run/client"
            if (!file(clientDir).exists()) {
                mkdir(clientDir)
            }
            workingDir = file(clientDir)
        }

        server {
            var serverDir = "run/server"
            if (!file(serverDir).exists()) {
                mkdir(serverDir)
            }
            workingDir = file(serverDir)
        }

        data {
            workingDir = file('runs/data')
            args '--mod', mod_id, '--all', '--output', file('src/generated/resources/'), '--existing', file('src/main/resources/')
        }
    }
}

sourceSets.main.resources.srcDir 'src/generated/resources'

repositories {
    maven minecraft.mavenizer
    maven fg.forgeMaven
    maven fg.minecraftLibsMaven
}

dependencies {
    implementation minecraft.dependency("net.minecraftforge:forge:${minecraft_version}-${forge_version}")

    // Forge 1.21.6+ uses EventBus 7, which shifts most of its runtime validation to compile-time via an annotation processor
    // to improve performance in production environments. This line is required to enable said compile-time validation
    // in your development environment, helping you catch issues early.
    annotationProcessor 'net.minecraftforge:eventbus-validator:7.0-beta.10'

    // Serene Seasons
    modCompileOnly "com.github.glitchfiend:SereneSeasons-forge:${project.serene_seasons_version}"
    modCompileOnly "com.github.glitchfiend:GlitchCore-forge:${project.glitchcore_version}"
    compileOnly("net.jodah:typetools:0.6.3")

    // Terrafirmacraft
    modCompileOnly "maven.modrinth:terrafirmacraft:${project.terrafirmacraft_version}"
    modCompileOnly "maven.modrinth:patchouli:${project.patchouli_version}-neoforge"
    modCompileOnly "maven.modrinth:barrels-2012:${project.barrels_version}"

    // Ecliptic Seasons
    modCompileOnly "curse.maven:ecliptic-seasons-1118306:${project.ecliptic_seasons_version}"

    // Xaero's Minimap
    modCompileOnly "maven.modrinth:xaeros-minimap:${project.xaeros_minimap_version}_Forge_${project.xaero_mc_version}"
    modCompileOnly "xaero.lib:xaerolib-forge-${project.xaero_mc_version}:${project.xaero_lib_version}"

    // JourneyMap
    compileOnly group: 'info.journeymap', name: 'journeymap-api-forge', version: project.journeymap_api_version, changing: true
    modCompileOnly "maven.modrinth:journeymap:${project.journeymap_version_forge}"

    //FTB Chunks + Dependencies
//    modCompileOnly "dev.ftb.mods:ftb-library-forge:${project.ftb_library_version}"
//    modCompileOnly "dev.ftb.mods:ftb-teams-forge:${project.ftb_teams_version}"
//    modCompileOnly "dev.ftb.mods:ftb-chunks-forge:${project.ftb_chunks_version}"
//    modCompileOnly "maven.modrinth:architectury-api:${project.architectury_version}+forge"

    // Map Atlases
//    modCompileOnly "maven.modrinth:map-atlases-forge:${project.map_atlases_version}"
//    modCompileOnly "maven.modrinth:moonlight:${project.moonlight_version_forge}"

    // Forge Config API Port
    modApi "fuzs.forgeconfigapiport:forgeconfigapiport-forge:${project.forge_config_api_port_version}"
    modImplementation("maven.modrinth:forge-config-api-port:v${project.forge_config_api_port_version}-${project.minecraft_version}-Forge") {
        exclude group: 'net.fabricmc', module: 'fabric-loader'
    }

    // Development QOL
    implementation("me.djtheredstoner:DevAuth-forge-latest:${devauth_version}")

    // Minimap Mod Dev Tests
    // See root gradle.properties to choose which to use at runtime.
    switch (project.minimap_mod.toLowerCase(Locale.ROOT)) {
        case "xaero":
            modImplementation "maven.modrinth:xaeros-minimap:${project.xaeros_minimap_version}_Forge_${project.xaero_mc_version}"
            modImplementation "xaero.lib:xaerolib-forge-${project.xaero_mc_version}:${project.xaero_lib_version}"
            break
        case "journey":
            modImplementation group: 'info.journeymap', name: 'journeymap-api-forge', version: project.journeymap_api_version, changing: true
            modLocalRuntime "maven.modrinth:journeymap:${project.journeymap_version_forge}"
            modLocalRuntime("maven.modrinth:common-network:${project.common_network_version}-forge")
            break
        case "ftb":
            break
        case "atlas":
            break
        case "none":
            break
        default: println("Unknown minimap mod specified: ${project.minimap_mod}. Must be xaero, journey, ftb, " +
                "atlas, or none")
    }

    // Season Mod Dev Tests (Forge)
    // See root gradle.properties to choose which to use at runtime.
    switch (project.season_mod_forge.toLowerCase(Locale.ROOT)) {
        case "serene":
            modImplementation "com.github.glitchfiend:SereneSeasons-forge:${project.serene_seasons_version}"
            modImplementation "com.github.glitchfiend:GlitchCore-forge:${project.glitchcore_version}"
            implementation("net.jodah:typetools:0.6.3")
            break
        case "terra":
            modImplementation "maven.modrinth:terrafirmacraft:${project.terrafirmacraft_version}"
            modImplementation "maven.modrinth:patchouli:${project.patchouli_version}-neoforge"
            //modImplementation "maven.modrinth:curios:${project.curios_version}"
            modImplementation "maven.modrinth:barrels-2012:${project.barrels_version}"
            break
        case "ecliptic":
            modImplementation "curse.maven:ecliptic-seasons-1118306:${project.ecliptic_seasons_version}"
            break
        default: println("Unknown season mod specified: ${project.season_mod_forge}. Must be serene, terra, or ecliptic")
    }
}

publishing {
    publications {
        mavenJava(MavenPublication) {
        }
    }
}

publishMods {
    displayName = "${mod_id}-forge-${minecraft_version}-${mod_version}"
    version = "${minecraft_version}-${mod_version}"
    file project(":forge")
    modLoaders.add("forge")

    def cfOptions = curseforgeOptions {
        accessToken = System.getenv("CURSEFORGE_TOKEN")
        changelogType = "markdown"
        javaVersions.add(JavaVersion.toVersion(project.java_version))
        minecraftVersions.addAll(curseforge_gameVersions.split(","))
        projectId = project.curseforge_forge_id
    }

    def mrOptions = modrinthOptions {
        accessToken = System.getenv("MODRINTH_TOKEN")
        minecraftVersions.addAll(modrinth_gameVersions.split(","))
        projectId = project.modrinth_forge_id
    }

    curseforge("curseforgeForge") {
        from cfOptions

        if (minecraft_version == "1.20.1") {
            modLoaders.add("neoforge")
        }

        optional("serene-seasons", "terrafirmacraft", "ecliptic-seasons")
        optional("ftb-chunks-forge", "journeymap", "xaeros-minimap", "xaeros-minimap-fair-play-edition", "map-atlases-forge")
        optional("curios", "accessories")
    }

    modrinth("modrinthForge") {
        from mrOptions

        if (minecraft_version == "1.20.1") {
            modLoaders.add("neoforge")
        }

        optional("serene-seasons", "terrafirmacraft", "ecliptic-seasons")
        optional("journeymap", "xaeros-minimap", "xaeros-minimap-fair-play-edition", "map-atlases-forge")
        optional("curios", "accessories")
    }
}