plugins {
    id 'multiloader-loader'
    id 'net.neoforged.moddev.legacyforge'
}

mixin {
    add(sourceSets.main, "${mod_id}.refmap.json")

    config("${mod_id}.mixins.json")

    if (project(":forge").file("src/main/resources/${mod_id}.forge.mixins.json").exists()) {
        config("${mod_id}.forge.mixins.json")
    }
}

legacyForge {
    version = forge_version

    validateAccessTransformers = true

    def at = project(':common').file('src/main/resources/META-INF/accesstransformer.cfg')
    if (at.exists()) {
        accessTransformers = ["src/main/resources/META-INF/accesstransformer.cfg"]
    }
    parchment {
        minecraftVersion = parchment_minecraft
        mappingsVersion = parchment_version
    }
    runs {
        client {
            client()
            var clientDir = "run/client"
            if (!file(clientDir).exists()) {
                mkdir(clientDir)
            }
            setGameDirectory(file(clientDir))
        }
        data {
            data()
            programArguments.addAll '--mod', project.mod_id, '--all', '--output', file('src/generated/resources/').getAbsolutePath(), '--existing', file('src/main/resources/').getAbsolutePath()
        }
        server {
            server()
            var serverDir = "run/server"
            if (!file(serverDir).exists()) {
                mkdir(serverDir)
            }
            setGameDirectory(file(serverDir))
        }
    }

    mods {
        "${mod_id}" {
            sourceSet sourceSets.main
            sourceSet project(":common").sourceSets.main
        }
    }
}

sourceSets.main.resources.srcDir 'src/generated/resources'

repositories {
    mavenCentral()

    maven {
        url = uri("https://repo.spongepowered.org/maven")
    }

    maven {
        name = 'Forge'
        url = uri('https://maven.minecraftforge.net/')
        content {
            includeGroup "net.minecraftforge"
        }
    }


    maven {
        name = "CurseMaven"
        url = uri("https://cursemaven.com")

        content {
            includeGroup "curse.maven"
        }
    }


    maven {
        name = "Modrinth Maven"
        url = uri("https://api.modrinth.com/maven")

        content {
            includeGroup "maven.modrinth"
        }
    }

    maven {
        name = "Forge Config API Port Maven"
        url = uri("https://raw.githubusercontent.com/Fuzss/modresources/main/maven/")
        content {
            includeGroup "fuzs.forgeconfigapiport"
        }
    }

    maven {
        name = "DevAuth Maven"
        url = uri("https://pkgs.dev.azure.com/djtheredstoner/DevAuth/_packaging/public/maven/v1")
        content {
            includeGroup "me.djtheredstoner"
        }
    }

    maven {
        name = 'Serene Seasons'
        url = uri('https://maven.minecraftforge.net/releases')
        content {
            includeGroup "com.github.glitchfiend"
        }
    }

    maven {
        name = "FTB Maven"
        url = uri("https://maven.ftb.dev/releases")
        content {
            includeGroup "dev.ftb.mods"
        }
    }

    maven {
        name = "shedaniel Maven"
        url = uri("https://maven.shedaniel.me/")
        content {
            includeGroup "me.shedaniel"
            includeGroup "dev.architectury"
            includeGroup "me.shedaniel.cloth"
        }
    }

    maven {
        // location of the maven that hosts JEI files since January 2023
        name = "Jared's maven"
        url = "https://maven.blamejared.com/"
        content {
            includeGroup "mezz.jei"
            includeGroup "info.journeymap"
        }
    }

    maven {
        name = "Xaero Maven"
        url = uri("https://chocolateminecraft.com/maven")
        content {
            includeGroup "xaero.lib"
            includeGroup "xaero.minimap"
        }
    }

    maven {
        name = "Journeymap API MAven"
        url = uri("https://jm.gserv.me/repository/maven-public/")
        content {
            includeGroup "info.journeymap"
        }
    }

    maven {
        name = "Homeostatic Seasons"
        url = uri("https://raw.githubusercontent.com/wendall911/maven/main/")
        content {
            includeGroup "com.github.wendall911.climatesettings"
            includeGroup "com.github.wendall911.homeostaticseasons"
            includeGroup "technology.roughness.whitenoise"
        }
    }

    maven {
        name = "Accessories Maven"
        url = uri("https://maven.wispforest.io/releases")
        content {
            includeGroup "io.wispforest"
            includeGroup "io.wispforest.endec"
        }
    }

    maven {
        name = "Sinytra Maven"
        url = uri("https://maven.su5ed.dev/releases")
    }

    maven {
        name = "ModMaven (Backup)"
        url = uri("https://modmaven.dev/")
    }

    maven {
        name = "Curios Maven"
        url = uri("https://maven.theillusivec4.top/")
    }
}

dependencies {
    annotationProcessor("org.spongepowered:mixin:${project.mixin_version}:processor")
    compileOnly(annotationProcessor("io.github.llamalad7:mixinextras-common:${project.mixin_extras_version}"))

    //Serene Seasons
    modCompileOnly "maven.modrinth:serene-seasons:${project.serene_seasons_version}-forge"

    // Terrafirmacraft
    modCompileOnly "maven.modrinth:terrafirmacraft:${project.terrafirmacraft_version}"
    modCompileOnly "maven.modrinth:patchouli:${project.patchouli_version}-forge"
    modCompileOnly "maven.modrinth:barrels-2012:${project.barrels_version}"

    // Ecliptic Seasons
    modCompileOnly "curse.maven:ecliptic-seasons-1118306:${project.ecliptic_seasons_version}"

    // Xaero's Minimap
    modCompileOnly "xaero.minimap:xaerominimap-forge-${project.xaero_mc_version}:${project.xaero_minimap_version}"
    modCompileOnly "xaero.lib:xaerolib-forge-${project.xaero_mc_version}:${project.xaero_lib_version}"

    // JourneyMap
    modCompileOnly "maven.modrinth:journeymap:${project.journeymap_version_forge}"

    //FTB Chunks + Dependencies
    modCompileOnly "dev.ftb.mods:ftb-library-forge:${project.ftb_library_version}"
    modCompileOnly "dev.ftb.mods:ftb-teams-forge:${project.ftb_teams_version}"
    modCompileOnly "dev.ftb.mods:ftb-chunks-forge:${project.ftb_chunks_version}"
    modCompileOnly "maven.modrinth:architectury-api:${project.architectury_version}+forge"

    //Map Atlases
    modCompileOnly "curse.maven:map-atlases-forge-519759:${project.map_atlases_forge_version}"
    modCompileOnly "maven.modrinth:moonlight:${project.moonlight_version_forge}"

    // Curios
    modCompileOnly "top.theillusivec4.curios:curios-forge:${project.curios_version}"
    modCompileOnly "top.theillusivec4.curios:curios-forge:${project.curios_version}:api"

    // Development QOL
    implementation("me.djtheredstoner:DevAuth-forge-latest:${devauth_version}")

    // Minimap Mod Dev Tests
    // See root gradle.properties to choose which to use at runtime.
    switch (project.minimap_mod.toLowerCase(Locale.ROOT)) {
        case "xaero":
            modImplementation "xaero.minimap:xaerominimap-forge-${project.xaero_mc_version}:${project.xaero_minimap_version}"
            modImplementation "xaero.lib:xaerolib-forge-${project.xaero_mc_version}:${project.xaero_lib_version}"
            break
        case "journey":
            modImplementation "maven.modrinth:journeymap:${project.journeymap_version_forge}"
            break
        case "ftb":
            modImplementation ("dev.ftb.mods:ftb-library-forge:${project.ftb_library_version}"){ transitive = false }
            modImplementation ("dev.ftb.mods:ftb-teams-forge:${project.ftb_teams_version}"){ transitive = false }
            modImplementation ("dev.ftb.mods:ftb-chunks-forge:${project.ftb_chunks_version}"){ transitive = false }
            modApi "maven.modrinth:architectury-api:${project.architectury_version}+forge"
            implementation("io.github.llamalad7:mixinextras-forge:${project.mixin_extras_version}")
            break
        case "atlas":
            modImplementation "maven.modrinth:map-atlases-forge:${project.map_atlases_version}"
            modImplementation "maven.modrinth:moonlight:${project.moonlight_version_forge}"
            break
        case "none":
            break
        default:
            println("Unknown minimap mod specified: ${project.minimap_mod}. Must be xaero, journey, ftb, atlas, or none")
            break
    }

    // Season Mod Dev Tests (Forge)
    // See root gradle.properties to choose which to use at runtime.
    switch (project.season_mod_forge.toLowerCase(Locale.ROOT)) {
        case "serene":
            modImplementation "maven.modrinth:serene-seasons:${project.serene_seasons_version}-forge"
            break
        case "terra":
            modImplementation "maven.modrinth:terrafirmacraft:${project.terrafirmacraft_version}"
            modImplementation "maven.modrinth:patchouli:${project.patchouli_version}-forge"
            modImplementation "maven.modrinth:curios:${project.curios_version}"
            modImplementation "maven.modrinth:barrels-2012:${project.barrels_version}"
            break
        case "ecliptic":
            modImplementation "curse.maven:ecliptic-seasons-1118306:${project.ecliptic_seasons_version}"
            break
        default:
            println("Unknown season mod specified: ${project.season_mod_forge}. Must be serene, terra, or ecliptic")
            break
    }
}

jar {
    finalizedBy('reobfJar')

    if (project(":forge").file("src/main/resources/${mod_id}.forge.mixins.json").exists()) {
        manifest.attributes([
                "MixinConfigs": "${mod_id}.mixins.json,${mod_id}.forge.mixins.json"
        ])
    } else {
        manifest.attributes([
                "MixinConfigs": "${mod_id}.mixins.json"
        ])
    }
}

publishing {
    publications {
        mavenJava(MavenPublication) {
        }
    }
}

sourceSets.each {
    def dir = layout.buildDirectory.dir("sourcesSets/$it.name")
    it.output.resourcesDir = dir
    it.java.destinationDirectory = dir
}

// Implement mcgradleconventions loader attribute
def loaderAttribute = Attribute.of('io.github.mcgradleconventions.loader', String)
['apiElements', 'runtimeElements'].each { variant ->
    configurations.named("$variant") {
        attributes {
            attribute(loaderAttribute, 'forge')
        }
    }
}
sourceSets.configureEach {
    [it.compileClasspathConfigurationName, it.runtimeClasspathConfigurationName].each { variant ->
        configurations.named("$variant") {
            attributes {
                attribute(loaderAttribute, 'forge')
            }
        }
    }
}

publishMods {
    displayName = "${mod_id}-forge-${minecraft_version}-${mod_version}"
    version = "${minecraft_version}-${mod_version}"
    file = tasks.reobfJar.archiveFile
    modLoaders.add("forge")

    def cfOptions = curseforgeOptions {
        accessToken = System.getenv("CURSEFORGE_TOKEN")
        changelogType = "markdown"
        javaVersions.add(JavaVersion.toVersion(project.java_version))
        minecraftVersions.addAll(curseforge_gameVersions.split(","))
        projectId = project.curseforge_forge_id
    }

    def mrOptions = modrinthOptions {
        accessToken = System.getenv("MODRINTH_TOKEN")
        minecraftVersions.addAll(modrinth_gameVersions.split(","))
        projectId = project.modrinth_forge_id
    }

    curseforge("curseforgeForge") {
        from cfOptions

        if (minecraft_version == "1.20.1") {
            modLoaders.addAll("forge", "neoforge")
        }

        optional("serene-seasons", "terrafirmacraft", "ecliptic-seasons")
        optional("ftb-chunks-forge", "journeymap", "xaeros-minimap", "xaeros-minimap-fair-play-edition", "map-atlases-forge")
        optional("curios", "accessories")
    }

    modrinth("modrinthForge") {
        from mrOptions

        if (minecraft_version == "1.20.1") {
            modLoaders.addAll("forge", "neoforge")
        }

        optional("serene-seasons", "terrafirmacraft")
        optional("journeymap", "xaeros-minimap", "xaeros-minimap-fair", "map-atlases-forge")
        optional("curios", "accessories")
    }
}