modLoader = "javafml" #mandatory
loaderVersion = "${neoforge_loader_version_range}" #mandatory
license = "${license}"

[[mods]] #mandatory
modId = "${mod_id}" #mandatory
version = "${version}" #mandatory
displayName = "${mod_name}" #mandatory
displayURL = "https://www.curseforge.com/minecraft/mc-mods/seasonhud"
logoFile = "${mod_id}.png"
authors = "${mod_author}" #optional
description = '''${description}'''

[[mixins]]
config = "${mod_id}.mixins.json"

[[mixins]]
config = "${mod_id}.neoforge.mixins.json"

# A dependency - use the . to indicate dependency for a specific modid. Dependencies are optional.
[[dependencies.${ mod_id }]] #optional
modId = "neoforge"
type = "required"
versionRange = "${neoforge_version_range}" #mandatory
ordering = "NONE"
side = "BOTH"

[[dependencies.${ mod_id }]]
modId = "minecraft"
type = "required"
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "BOTH"

#[[dependencies.${mod_id}]]
#    modId = "sereneseasons"
#    type="required"
#    versionRange = "[1.20.4-9.3.0.13,)"
#    ordering = "AFTER"
#    side = "BOTH"

[[dependencies.${ mod_id }]]
modId = "xaerominimap"
type = "optional"
versionRange = "[23.9.4,)"
ordering = "AFTER"
side = "CLIENT"