plugins {
    id 'com.gradleup.shadow'
    id 'net.darkhax.curseforgegradle'
    id 'com.modrinth.minotaur'
}

loom {
    runs {
        client {
            client()
            setConfigName("NeoForge Client")
            ideConfigGenerated(true)
            runDir("run-client")
        }
        server {
            server()
            setConfigName("NeoForge Server")
            ideConfigGenerated(true)
            runDir("run-server")
        }
    }
}

architectury {
    platformSetupLoomIde()
    neoForge()
}

configurations {
    common {
        canBeResolved = true
        canBeConsumed = false
    }
    compileClasspath.extendsFrom common
    runtimeClasspath.extendsFrom common
    developmentNeoForge.extendsFrom common

    // Files in this configuration will be bundled into your mod using the Shadow plugin.
    // Don't use the `shadow` configuration from the plugin itself as it's meant for excluding files.
    shadowBundle {
        canBeResolved = true
        canBeConsumed = false
    }
}

dependencies {
    neoForge "net.neoforged:neoforge:${project.neoforge_version}"

    common(project(path: ':common', configuration: 'namedElements')) { transitive false }
    shadowBundle project(path: ':common', configuration: 'transformProductionNeoForge')

    // Serene Seasons
    modCompileOnly "com.github.glitchfiend:SereneSeasons-neoforge:${project.serene_seasons_version}"
    modCompileOnly "com.github.glitchfiend:GlitchCore-neoforge:${project.glitchcore_version}"
    modCompileOnly("net.jodah:typetools:0.6.3")

    // Terrafirmacraft
    modCompileOnly "maven.modrinth:terrafirmacraft:${project.terrafirmacraft_version}"
    modCompileOnly "maven.modrinth:patchouli:${project.patchouli_version}-neoforge"

    // Ecliptic Seasons
    modCompileOnly "curse.maven:ecliptic-seasons-1118306:${project.ecliptic_seasons_version}"

    // Xaero's Minimap
    modCompileOnly "maven.modrinth:xaeros-minimap:${project.xaeros_minimap_version}_NeoForge_1.21"
    modCompileOnly "xaero.lib:xaerolib-neoforge-1.21:${project.xaero_lib_version}"

    // JourneyMap
    compileOnly group: 'info.journeymap', name: 'journeymap-api-neoforge', version: project.journeymap_api_version, changing: true
    modCompileOnly "maven.modrinth:journeymap:${project.journeymap_version_neoforge}"

    // FTB Chunks + Dependencies
    modCompileOnly "dev.ftb.mods:ftb-library-neoforge:${project.ftb_library_version}"
    modCompileOnly "dev.ftb.mods:ftb-teams-neoforge:${project.ftb_teams_version}"
    modCompileOnly "dev.ftb.mods:ftb-chunks-neoforge:${project.ftb_chunks_version}"
    modCompileOnly "dev.architectury:architectury-neoforge:${project.architectury_version}"

    // Map Atlases
    modCompileOnly "maven.modrinth:map-atlases-forge:${project.map_atlases_version_neoforge}"
    modCompileOnly "maven.modrinth:moonlight:${project.moonlight_version_neoforge}"
    modCompileOnly "maven.modrinth:immediatelyfast:${project.immediatelyfast_version}+${project.minecraft_version}-neoforge"

    // Curios
    modCompileOnly "top.theillusivec4.curios:curios-neoforge:${project.curios_version}"
    modCompileOnlyApi "top.theillusivec4.curios:curios-neoforge:${project.curios_version}:api"

    // Accessories
    modCompileOnly("io.wispforest:accessories-neoforge:${project.accessories_version}")
    modCompileOnly("me.shedaniel.cloth:cloth-config-neoforge:${project.cloth_config_version}") {
        exclude(group: "net.fabricmc.fabric-api")
    }

    // Development QOL
    modLocalRuntime "me.djtheredstoner:DevAuth-neoforge:${project.devauth_version}"
//    modLocalRuntime "maven.modrinth:sodium:${project.sodium_version_neoforge}"

//    modLocalRuntime("maven.modrinth:text-animator:${project.text_animator_version_neoforge}")

    // Minimap Mod Dev Tests
    // See root gradle.properties to choose which to use at runtime.
    switch (project.minimap_mod.toLowerCase(Locale.ROOT)) {
        case "xaero":
            modLocalRuntime "maven.modrinth:xaeros-minimap:${project.xaeros_minimap_version}_NeoForge_1.21"
            modImplementation "xaero.lib:xaerolib-neoforge-1.21:${project.xaero_lib_version}"
            break
        case "journey":
            implementation group: 'info.journeymap', name: 'journeymap-api-neoforge', version: project.journeymap_api_version, changing: true
            modImplementation "maven.modrinth:journeymap:${project.journeymap_version_neoforge}"
            modImplementation("maven.modrinth:common-network:${project.common_network_version}-neoforge")
            break
        case "ftb":
            modLocalRuntime "dev.ftb.mods:ftb-library-neoforge:${project.ftb_library_version}"
            modLocalRuntime "dev.ftb.mods:ftb-teams-neoforge:${project.ftb_teams_version}"
            modLocalRuntime "dev.ftb.mods:ftb-chunks-neoforge:${project.ftb_chunks_version}"
            modImplementation "dev.architectury:architectury-neoforge:${project.architectury_version}"
            break
        case "atlas":
            modLocalRuntime "maven.modrinth:map-atlases-forge:${project.map_atlases_version_neoforge}"
            modLocalRuntime "maven.modrinth:moonlight:${project.moonlight_version_neoforge}"
            modLocalRuntime "maven.modrinth:immediatelyfast:${project.immediatelyfast_version}+1.21.1-neoforge"
            break
        case "none":
            break
        default: println("Unknown recipe viewer specified: ${project.minimap_mod}. Must be xaero, journey, ftb, " +
                "atlas, or none")
    }

    // Season Mod Dev Tests (Forge)
    // See root gradle.properties to choose which to use at runtime.
    switch (project.season_mod_neoforge.toLowerCase(Locale.ROOT)) {
        case "serene":
            modLocalRuntime "com.github.glitchfiend:SereneSeasons-neoforge:${project.serene_seasons_version}"
            modLocalRuntime "com.github.glitchfiend:GlitchCore-neoforge:${project.glitchcore_version}"
            modImplementation("net.jodah:typetools:0.6.3")
            break
        case "terra":
            modImplementation "maven.modrinth:terrafirmacraft:${project.terrafirmacraft_version}"
            modImplementation "maven.modrinth:patchouli:${project.patchouli_version}-neoforge"
            break
        case "ecliptic":
            modImplementation "curse.maven:ecliptic-seasons-1118306:${project.ecliptic_seasons_version}"
            break
        default: println("Unknown season mod specified: ${project.minimap_mod}. Must be serene, terra, or ecliptic")
    }

    // Accessory Mod Dev Tests
    // See root gradle.properties to choose which to use at runtime.
    switch (project.accessory_mod.toLowerCase(Locale.ROOT)) {
        case "accessories":
            modLocalRuntime "io.wispforest:accessories-neoforge:${project.accessories_version}"
            modLocalRuntime "io.wispforest:owo-lib-neoforge:${project.owo_version_neoforge}"
            modLocalRuntime("me.shedaniel.cloth:cloth-config-neoforge:${project.cloth_config_version}") {
                exclude(group: "fabric-api")
            }

            forgeRuntimeLibrary(implementation("blue.endless:jankson:1.2.2"))

            forgeRuntimeLibrary("io.wispforest:endec:${project.endec_version}")
            forgeRuntimeLibrary("io.wispforest.endec:gson:${project.endec_gson_version}")
            forgeRuntimeLibrary("io.wispforest.endec:jankson:${project.endec_jankson_version}")
            forgeRuntimeLibrary("io.wispforest.endec:netty:${project.endec_netty_version}")

            break
        case "none":
            break
        default: println("Unknown accessory mod specified: ${project.minimap_mod}. Must be accessories, or none")
    }
}

shadowJar {
    configurations = [project.configurations.shadowBundle]
    archiveClassifier = 'dev-shadow'
}

remapJar {
    inputFile.set shadowJar.archiveFile
}

modrinth {
    debugMode = false
    token = System.getenv("MODRINTH_TOKEN")
    projectId = modrinth_forge_id
    versionNumber = minecraft_version + "-" + version
    versionName = base.archivesName.get() + "-" + mod_version
    versionType = "release"
    uploadFile = remapJar

    List<String> mcVersions = modrinth_gameVersions.split(",")
    gameVersions = mcVersions
    loaders = ["neoforge"]

    changelog = projectDir.toPath().getParent().resolve("LATEST_CHANGELOG.md").getText()

    dependencies {
        optional.project "serene-seasons"
        optional.project "terrafirmacraft"
        optional.project "curios"
        optional.project "accessories"
        optional.project "xaeros-minimap"
        optional.project "xaeros-minimap-fair"
        optional.project "journeymap"
        optional.project "map-atlases"
    }
}

tasks.register('publishCurseForge', net.darkhax.curseforgegradle.TaskPublishCurseForge) {
    debugMode = false
    disableVersionDetection()
    apiToken = System.getenv("CURSEFORGE_TOKEN")

    def mainFile = upload(curseforge_forge_id, remapJar)
    mainFile.changelogType = "markdown"
    mainFile.changelog = projectDir.toPath().getParent().resolve("LATEST_CHANGELOG.md").getText()
    mainFile.releaseType = "release"

    List<String> mcVersions = curseforge_gameVersions.split(",")
    mainFile.gameVersions = mcVersions
    mainFile.addGameVersion("NeoForge")
    mainFile.addJavaVersion("Java 21")

    mainFile.addOptional("serene-seasons")
    mainFile.addOptional("terrafirmacraft")
    mainFile.addOptional("ecliptic-seasons")
    mainFile.addOptional("curios")
    mainFile.addOptional("accessories")
    mainFile.addOptional("xaeros-minimap")
    mainFile.addOptional("xaeros-minimap-fair-play-edition")
    mainFile.addOptional("ftb-chunks-forge")
    mainFile.addOptional("journeymap")
    mainFile.addOptional("map-atlases-forge")
}

tasks.register('publishNeoForge') {
    group = "upload"
    dependsOn(tasks.publishCurseForge)
    dependsOn(tasks.modrinth)
}