name: Releases

on: 
  push:
    branches:
      - active/multi/1.20.1
    tags:
    - '*'

jobs:

  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4
    - uses: ncipollo/release-action@v1
      with:
        bodyFile: "LATEST_CHANGELOG.md"
