name: MC-Publish Multiloader (CurseForge/Modrinth)

on: [workflow_dispatch]

env:
  MINECRAFT_VERSION: |
    [1.20,1.20.2)
  MOD_VERSION: 1.5.10
  JAVA_VERSION: 17

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check Environment Variables
        run: env

      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: "temurin"
          java-version: 17

      - name: Make Gradle Wrapper Executable
        if: ${{ runner.os != 'Windows' }}
        run: chmod +x ./gradlew

      - name: Build
        run: ./gradlew clean build

      - name: Publish on Curseforge and Modrinth (Forge)
        uses: Kir-Antipov/mc-publish@v3.3
        with:

          modrinth-featured: true
          modrinth-id: VNjUn3NA
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}

          curseforge-id: 690971
          curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}

          files: forge/build/libs/!(*-@(dev|sources|javadoc)).jar

          name: ""
          version: "forge-1.20.1-${{env.MOD_VERSION}}"
          version-type: release
          changelog-file: CHANGELOG.md

          dependencies: |
            curios(recommended)
            ftb-chunks-forge(recommended)
            journeymap(recommended)
            xaeros-minimap(recommended)
            xaeros-minimap-fair-play-edition(recommended)
            serene-seasons(required)

          loaders: forge
          game-versions: |
            [1.20,1.20.2)
          java: "${{env.JAVA_VERSION}}"

      - name: Publish on Curseforge and Modrinth (Fabric)
        uses: Kir-Antipov/mc-publish@v3.3
        with:

          modrinth-featured: true
          modrinth-id: iDiIfZLX
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}

          curseforge-id: 848022
          curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}

          files: fabric/build/libs/!(*-@(dev|sources|javadoc)).jar

          name: ""
          version: "fabric-1.20.1-${{env.MOD_VERSION}}"
          version-type: release
          changelog-file: CHANGELOG.md

          dependencies: |
            trinkets(recommended)
            ftb-chunks-fabric(recommended)
            journeymap(recommended)
            xaeros-minimap(recommended)
            xaeros-minimap-fair-play-edition(recommended)
            fabric-seasons(required)
            fabric-seasons-extras(recommended)
            forge-config-api-port-fabric(required)

          loaders: fabric
          game-versions: |
            [1.20,1.20.2)
          java: "${{env.JAVA_VERSION}}"